services:
  server:
    build:
      context: .
    ports:
      - "8000:8080" # Map host port 8000 to the container's default port 8080
    env_file:
      - .env
    # This section sets the PORT variable for local docker-compose runs,
    # mimicking the behavior of cloud environments like Cloud Run.
    environment:
      - PORT=8080
    volumes:
      - .:/app
    # The CMD in the Dockerfile is now the source of truth, so the command
    # here is commented out. It's good practice to let the Dockerfile define
    # how the container runs.
    # command: gunicorn 'main:app' --workers 4 --bind 0.0.0.0:8080 --worker-class uvicorn.workers.UvicornWorker