"""Rename aprox_date to approx_date in PlannedExpense

Revision ID: 160cb2d2dc62
Revises: 8051daff38ec
Create Date: 2025-10-03 09:03:45.707487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "160cb2d2dc62"
down_revision: Union[str, None] = "8051daff38ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plannedexpense", sa.Column("approx_date", sa.Date(), nullable=False))
    op.drop_column("plannedexpense", "aprox_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plannedexpense",
        sa.Column("aprox_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("plannedexpense", "approx_date")
    # ### end Alembic commands ###
