name: Python CI

on:
  push:
    branches: [ "main" ]  # Run on push to the main branch. Change this if you are using a different branch.

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment. You are welcome to change this.

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest sqlmodel "python-dotenv"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        # Set environment variables required by the application for testing
        export DATABASE_URL="sqlite:///./ci_database.db"
        export SECRET_KEY="super-secret-key-for-ci-tests"
        export ALGORITHM="HS256"
        pytest