name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  # ----------------------------------------------------------------
  # CONTINUOUS INTEGRATION - Run on every push and pull request
  # ----------------------------------------------------------------
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest

  style:
    name: Check Code Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Black formatter check
        run: black --check .

  security:
    name: Run Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Bandit security scanner
        run: bandit -r . -x ./env,./tests

  # ------------------------------------------------------------------
  # CONTINUOUS DEPLOYMENT - Run only on push/merge to main
  # ------------------------------------------------------------------
  deploy:
    name: Deploy to Google Cloud Run
    needs: [test, style, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          docker build -t veronicalobos87/marginal-wallet-api:latest .
          docker push veronicalobos87/marginal-wallet-api:latest

      - name: Install Dependencies for Migrations
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: alembic upgrade head

      - name: Deploy to Cloud Run
        run: >-
          gcloud run deploy marginal-wallet-api
          --image docker.io/veronicalobos87/marginal-wallet-api:latest
          --region us-central1
          --allow-unauthenticated
          --project ${{ secrets.GCP_PROJECT_ID }}
          --set-env-vars "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }},SECRET_KEY=${{ secrets.SECRET_KEY }},ALGORITHM=${{ secrets.ALGORITHM }},ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }},GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}"
          --max-instances=4
